### ISSUE TITLE
Icon shows -1 instead of count over a certain threshold

### ISSUE THREAD

**Issue by jwhipp** [psxpaul/office365-checker#13]
I am noticing that when I have what I think is 10+ emails, the icon shows -1 instead of the count.

I am trying to track down the exact number, keeping an eye on it now.

**Comment by jwhipp** [comment]
It is indeed >= 10.

**Comment by psxpaul** [comment]
Thank you for bringing this to my attention. Office365 looks like their API is returning -1 for some reason, now, but I was able to use a different REST url for the same data. This should be fixed in 0.0.21.
