### ISSUE TITLE
The extension does not keep the name and password

### ISSUE THREAD

**Issue by Ziggy2Man** [psxpaul/office365-checker#2]
Whenever I launch the browser I need to re-enter the name and password. Can cause the extension to keep it regularly?

I use Opera 29.

**Comment by psxpaul** [comment]
Thanks for the feedback!

I originally didn't want to save passwords, since it would be a security concern. I think having an option to turn it on/off would work, for those that don't care. I'll add this, along with issue #1, to my list of todos.

**Comment by Ziggy2Man** [comment]
Thank you for your attention.
This function will be very useful for me, as I'm sure for many others.
Thanks again.

**Comment by swinterroth** [comment]
+1 I like this app but I don't like the fact that I need to renter my UN and PW.  Even if it somehow checked to see if I was logged into the the email client first or if the username and password fields were in HTML so I could auto login with Dashlane or OnePass.

**Comment by psxpaul** [comment]
This should be fixed with the 0.0.17 version I just pushed out. If you choose not to save your credentials, it will continue to open a new tab to login with. Saved credentials are stored to chrome's sync storage, with a two-way encryption (courtesy of sjcl).

**Comment by GermanKiwi** [comment]
Hi @psxpaul I love this extension, and I'm using v0.0.17 right now. However it's not remembering my credentials when I restart Chrome. I right-click on the toolbar icon, select Options, check "Save username/password" and enter mine into the fields there - and this works for the duration of the Chrome session. But when I restart Chrome, the credentials are gone and "Save username/password" is no longer checked anymore.

Any ideas why that is?

**Comment by GermanKiwi** [comment]
Also, a small suggestion: it would be nice to have a "Save" or "OK" button on the options panel. It's not so intuitive to click the X in the top corner to exit the panel - normally clicking the X means "cancel" in many other apps. :)

**Comment by psxpaul** [comment]
Hi @GermanKiwi , what are you Chrome sync options? When you inspect the view for the extension, are there any errors?

As for the Save/OK buttons - yeah, I was thinking of adding those when I tackle issue #1 .

**Comment by Ziggy2Man** [comment]
@psxpaul The same for me.
I'm not use chrome at all, I'm using Opera browser so I can't answer your question about Chrome sync.

**Comment by GermanKiwi** [comment]
Hi @psxpaul, my Chrome sync options - I guess you mean when I go to chrome://settings/syncSetup - in there, I have "Sync everything", with literally every option enabled.

I'm not entirely sure what you mean about inspecting the view for the extension - can you clarify what/where this is?

**Comment by Ziggy2Man** [comment]
Thanks a lot. Version 0.0.18 works perfectly :)

**Comment by GermanKiwi** [comment]
Yup, 0.0.18 seems to be working for me too - after entering my credentials and then restarting Chrome, the credentials are still saved there after Chrome restarts. Thanks!! :)
