### ISSUE TITLE
Newer icon

### ISSUE THREAD

**Issue by hanthor** [psxpaul/office365-checker#4]
Updating to the newer version of the icons would be nice.

![office365_96](https://cloud.githubusercontent.com/assets/5840441/8458138/568b145c-1fe3-11e5-9bbf-98cb92b7e8f4.png)
![office365_logged_in](https://cloud.githubusercontent.com/assets/5840441/8458139/56a4201e-1fe3-11e5-8b0f-35c8b1638fbe.png)

**Comment by psxpaul** [comment]
Thanks! Updated in commit efda097f3dd6f9dfc32f262f2828f1e7fdd6698c. I will update in the chrome store shortly.
