### ISSUE TITLE
No longer functioning.

### ISSUE THREAD

**Issue by geckos17** [psxpaul/office365-checker#5]
Extension fails to display notifications.  Icon remains greyed out with question mark.  Still acts as a shortcut to inbox, however.

**Comment by psxpaul** [comment]
This should be fixed in commit 7df30da8d9e79fda5435f5970655951d32e18416, thanks to @wilriker. It will have the limitation of only showing the last 10 new messages though, until a better workaround can be found.

**Comment by wilriker** [comment]
Actually it would be possible to get all new messages from Inbox but that would require recursive loading of them in packs of max ten messages per request which could increase checking time and _if_ you have more than ten new messages, you should check your Inbox either way. ;-)

**Comment by psxpaul** [comment]
Yeah, I was thinking of just changing it to say "10+" when you have 10 unread messages, but I was hoping for an equivalent to the $count function instead. Any idea why that function went away? All I could find was this:

http://officespdev.uservoice.com/forums/224641-general/suggestions/8725678-office-365-api-query-count-on-messages-is-not-a

**Comment by wilriker** [comment]
To be honest, I have never looked at this API before trying to fix the Chrome extension (I was simply missing too many emails ;-)). Interestingly $count is still documented and a couple of code examples still use it.

I have no clue why such a basic function should have been removed intentionally. I can only assume/hope this is a bug in the API.

**Comment by wilriker** [comment]
Oh and just AS an aside: in my PR I was guessing that this might no longer be restricted to new messages in Inbox but it definitely still is.

**Comment by psxpaul** [comment]
I found a better fix for this - apparently using $count=true is what you have to do now. I'm pushing v0.0.16 now, so this should get fixed in the chrome store shortly.

**Comment by wilriker** [comment]
Great! :-)
